### ISSUE TITLE
Do you take requests?

### ISSUE THREAD

**Issue by Siber009** [Fl4sh9174/Switch-Ultrawide-Mods#1]
If so would you be able to make a 21:9 mod for Monster Hunter generation ultimate? If not no worries! Appreciate the collection regardless!

**Comment by Fl4sh9174** [comment]
Im not taking any requests atm, just updating the games i play, but you can use the guide posted by stevens teaching how to make these mods: https://github.com/StevensND/ghidra-port-mods-guide/tree/main/Aspect%20Ratio%20Mod%20Guide

**Comment by Siber009** [comment]
Hello sorry I have a follow up question as I'm struggling with this. I saw you made a mod for gu and I greatly appreciate it, is there a simple way to change the mod from 21:9 to 20:9? 

Do I just need to aspect ratio code with another value ?

**Comment by Fl4sh9174** [comment]
> Hello sorry I have a follow up question as I'm struggling with this. I saw you made a mod for gu and I greatly appreciate it, is there a simple way to change the mod from 21:9 to 20:9?
> 
> Do I just need to aspect ratio code with another value ?

GU?

**Comment by Siber009** [comment]
Amazing ! Thank you so much I really appreciate this alot !
