### ISSUE TITLE
FIFA 23

### ISSUE THREAD

**Issue by Boyyatio** [Fl4sh9174/Switch-Ultrawide-Mods#12]
Dear developer !
I would like to request ultrawide Mod for game "FIFA 23"
Hope you make this mod for gamer user. Thank you !

**Comment by Fl4sh9174** [comment]
Added the following mods:
- 21:9 Ultrawide
- 60FPS
- 120FPS

**Comment by Boyyatio** [comment]
Thank you so much for complete this request, after tested look running very smooth.
