### ISSUE TITLE
Pokémon Brilliant Diamond - Weirdly stretched Pokédex, Box and Catch screen

### ISSUE THREAD

**Issue by Loreciao** [Fl4sh9174/Switch-Ultrawide-Mods#13]
**Might also just be a UI/RomFS related issue, but I think it's worth nothing. Maybe it's fixable!**

![2](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/69169909/cb454c16-a8b0-4e11-8f40-096d997b7210)
![1](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/69169909/982d548a-11ca-488e-9316-534ec81ca9c1)
![3](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/69169909/5c0850de-3c50-4f20-adf0-144848d5cf65)

**Comment by Fl4sh9174** [comment]
HUD/UI is tied to the resolution, if i adjust the HUD to 21:9 image will be cropped, so this way the gameplay is okay, and you can navigate on menus without any problem, im trying to figure out a way to fix it but the game doesnt accept ultrawide very well.

**Comment by Loreciao** [comment]
Definitely not a dealbreaker, but it's still an interesting behaviour as it stretches in this weird way. 🙂
