### ISSUE TITLE
Request mod 1000xRESIST

### ISSUE THREAD

**Issue by Boyyatio** [Fl4sh9174/Switch-Ultrawide-Mods#15]
I would like to request mod ultrawide 20:9 with full UI of game 1000xRESIST ! Thank you.![39251156.jpg](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/165496235/5f0f7340-b1f3-4865-a925-2c5f8275b022)

**Comment by Fl4sh9174** [comment]
Send me the main of the latest update and ill check if its possible.
