### ISSUE TITLE
FIFA 23 mod 21:9 Cropped Screen 

### ISSUE THREAD

**Issue by Boyyatio** [Fl4sh9174/Switch-Ultrawide-Mods#16]
FIFA 23 look like cropped different from original UI and the logo is stretch also ![Screenshot_suyu Debug Release_20240509_235630.jpg](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/165496235/80b53bd9-55e7-4cf2-a4fd-5543a5b06fe0)

![Screenshot_suyu Debug Release_20240509_235442.jpg](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/165496235/b6abfa3f-1baa-4cf8-832a-06a0522ee5b6)

![Screenshot_suyu Debug Release_20240510_102159.jpg](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/165496235/5dd68cce-1a99-480f-92cc-81a8a3e21beb)

**Comment by Fl4sh9174** [comment]
Yes, the orignal UI is 16:9, to adjust the aspect ratio black bars are used.
