### ISSUE TITLE
Kirby's Return to Dream Land Deluxe

### ISSUE THREAD

**Issue by Loreciao** [Fl4sh9174/Switch-Ultrawide-Mods#17]
Hello,
I would kindly like to request an ultrawide mod for this game, as it's the only Kirby game without a similar mod left.
I hope it's not a hassle.

**Comment by Fl4sh9174** [comment]
Added it, test and let me know if its working.
some notes:
Title screen adjusted to 21:9
Overworld map adjusted for 21:9
Levels adjusted to 21:9
HUD/UI is tied to 16:9, so itll be stretched

Tried 2 levels and the game was runnig fine, no artifacts or weird behaviors.

**Comment by Loreciao** [comment]
Tested all the way through World 1 with no issues whatsoever. Thank you again!
