### ISSUE TITLE
zipfile blobs committed as-is to main are opaque and offer zero utility to anyone willing to offer patches or fixes to individual games.

### ISSUE THREAD

**Issue by ebelliveau** [Fl4sh9174/Switch-Ultrawide-Mods#2]
Committing zip blobs directly to main with a single commit message of "Updates" is functionally useless to anyone who wants to contribute to this repository.  Please consider committing the bare directories so people can fork the repo and submit PRs.  Otherwise, this repository is not accessible to actual developers who follow a proper trunk-based git flow.

Please consider fixing this.  This repository is offering high-value features to switch emu gamers, but the way it does so is totally opaque due to the use of zip blobs.

**Comment by Fl4sh9174** [comment]
I plan to change it in the future. At first, I made this repository to host it only; the zip blobs are for ease of use only
