### ISSUE TITLE
Can you make one for Skyward Sword HD and SM 3D All Stars?

### ISSUE THREAD

**Issue by 0Synergy** [Fl4sh9174/Switch-Ultrawide-Mods#23]
While im at it c-can we get 32:9 versions for these mods?

**Comment by Fl4sh9174** [comment]
3D All Stars i made the Ultrawide mod for the Mario Galaxy only, the sunshine i recommend you use dolphin, support, performance and mods are much better there compared to the emulator Nintendo is using on the switch version, and about the skyward Sword, ill take a look at it someday.
