### ISSUE TITLE
DKC ultrawide doesnt seems working, still stretching

### ISSUE THREAD

**Issue by mgemt** [Fl4sh9174/Switch-Ultrawide-Mods#24]
The game version is the same, but the ultrawide mod doesnt work, perhaps you missed uploading file on the zip? btw I'm using the [21.9 Ultrawide Default UI v1.0.2] .

*I have try your other mod TLOZ Breath of the wild ultrawide and its working though

**Comment by Fl4sh9174** [comment]
Mod is working fine, post screenshot with mod enabled/disabled to see if something is wrong.

**Comment by mgemt** [comment]
I set the aspect ratio to 21:9 or Strecth to windows but it still the same result
![1](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/44252828/98ba1915-80b1-444d-8d31-763583d6a864)
21:9
![2](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/44252828/e44b7130-1b9c-4e0a-8fb2-b775e5d3a260)
16:9
![3](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/44252828/2be6177b-8bf2-48b5-89b8-b7f1cebe41e7)

for me it seems still stretched

**Comment by Fl4sh9174** [comment]
![169](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/153722828/a0eeec31-ae55-4495-b32d-c28c25f50b2e)
![219](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/153722828/fb6829b3-9384-41b6-86bb-d40370b58a2b)

**Comment by Fl4sh9174** [comment]
I tested on yuzu/ryujinx and its working fine, and always use stretch to window option.

**Comment by Fl4sh9174** [comment]
![ui](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/153722828/7459982c-b629-4586-98a0-597df0cc3967)
Adjusted Ui version

**Comment by mgemt** [comment]
can I see the mod setting? do you use the [21.9 Ultrawide Default UI v1.0.2] only or with other option? because its a little confusing. I can't test with yuzu at the moment because i've got it uninstalled and can't find the backup :(
