### ISSUE TITLE
Mario Party Superstar 120Fps mod

### ISSUE THREAD

**Issue by Nassi88** [Fl4sh9174/Switch-Ultrawide-Mods#25]
In the mini game where the plates rotate, I could walk through the fence and didn't have to wait until the opening turned towards me. In the mini game where you cut out the ghost with the jackhammer, the time goes too quickly... I didn't test any other games.

**Comment by Fl4sh9174** [comment]
Yeah, the 120ps mod for this game has a lot of issues, had no time to fix it, will revisit it someday.
