### ISSUE TITLE
Fire Emblem Three Houses UW

### ISSUE THREAD

**Issue by Vatroki** [Fl4sh9174/Switch-Ultrawide-Mods#26]
Any chance of making ultrawide mod for FE3H?

**Comment by Fl4sh9174** [comment]
Added: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/Fire%20Emblem%20Three%20Houses%20%5B%5B21.9%20Ultrawide%20v1.2.0%5D%5D.zip
