### ISSUE TITLE
Hyrule Warriors Definitive Edition 

### ISSUE THREAD

**Issue by MajorasMaks** [Fl4sh9174/Switch-Ultrawide-Mods#28]
Could you, if possible, please make an ultrawide 21:9 mod for Hyrule Warriors DE

**Comment by Fl4sh9174** [comment]
Added: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/Hyrule%20Warriors%20Definitive%20Edition%20%5B21.9%20Ultrawide%20v1.2.0%5D.zip

**Comment by MajorasMaks** [comment]
Thank you so much! Could you please also add a 19.5:9 version, and is it
possible to fix the stretched hud? Either way thanks a lot I really
appreciate this!

**Comment by Fl4sh9174** [comment]
for 195:9 just replace this one with it:
@enabled
003df7d8 5901A852
003df7e0 79559572
@stop

About the HUD, i can change it, but it wont be centered, in fact even changing resolution is messing with the HUD, and it wont scale properly, so i just leave the HUD this way for now.

**Comment by MajorasMaks** [comment]
Oh ok thanks.
