### ISSUE TITLE
Fire Emblem Warriors 1.5.0

### ISSUE THREAD

**Issue by SnowVXIII** [Fl4sh9174/Switch-Ultrawide-Mods#29]
Can You please make a 21:9 - 3440x1440  for this game?.
 Thank you for your hardwork on other mods that save us from playing games on 16:9, ultrawide team

**Comment by Fl4sh9174** [comment]
Added: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/Fire%20Emblem%20Warriors%20%5B21.9%20Ultrawide%20v1.5.0%5D.zip
