### ISSUE TITLE
Link's Awakening 120FPS issue

### ISSUE THREAD

**Issue by igoticecream** [Fl4sh9174/Switch-Ultrawide-Mods#3]
Hello, I'm trying your 120FPS mod for LA, version 2 speed up the game and version 1 is kinda buggy (weird fish movement behavior, sword attack is faster, etc). Is there a way to be able to play 120fps without the speed up with v2?

**Comment by Fl4sh9174** [comment]
The mod require both files to work, and this version is WIP, ill update it when i have time.

**Comment by Fl4sh9174** [comment]
Just updated the mod, test it and report back if you find any issues.
