### ISSUE TITLE
Animal Well

### ISSUE THREAD

**Issue by kmo6rqb4** [Fl4sh9174/Switch-Ultrawide-Mods#31]
First of all, thank you very much for your work!

If you can, I would appreciate a 21:9 (or even better 20:9) ultrawide mod for Animal Well.

Thank you.

**Comment by Fl4sh9174** [comment]
Sadly the game gets cropped when i change the aspect ratio, seems like its using sprites at 16:9, and when i change aspect ratio its zoom out or stuff gets messed everywhere.
