### ISSUE TITLE
Red Dead Redemption (2023)

### ISSUE THREAD

**Issue by Uncloak2** [Fl4sh9174/Switch-Ultrawide-Mods#33]
would be cool to see some 60fps + 3440x1440 specific mods :) 

latest update is 1.0.4

**Comment by Fl4sh9174** [comment]
Keaton and Stevens posted the mods for this game on gamebanana, take a look.

**Comment by Uncloak2** [comment]
@Fl4sh9174 Sure but isn't the point to get them all in one place? You can always give credit here.

**Comment by StevensND** [comment]
> @Fl4sh9174 Sure but isn't the point to get them all in one place? You can always give credit here.

Just check our githubs lol
