### ISSUE TITLE
Mario + Rabbids: Kingdom Battle (2017)

### ISSUE THREAD

**Issue by Uncloak2** [Fl4sh9174/Switch-Ultrawide-Mods#35]
Ultrawide + 60fps+ if possible

latest update = 1.9

**Comment by Fl4sh9174** [comment]
added: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/Mario%20%2B%20Rabbids%20Kingdom%20Battle%20%5B21.9Ultrawide%20v1.9.589692%5D.zip
