### ISSUE TITLE
Captain Toad Treasure Tracker (2017)

### ISSUE THREAD

**Issue by Uncloak2** [Fl4sh9174/Switch-Ultrawide-Mods#36]
Ultrawide + 60FPS+

1.3.0 is latest update.

**Comment by Fl4sh9174** [comment]
Added: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/Captain%20Toad%20Treasure%20Tracker%20%5B21.9%20Ultrawide%20v1.3.0%5D.zip

**Comment by Fl4sh9174** [comment]
The mods inlcuded are:
Ultrawide
Disable FXAA
Disable DOF
Improved level of Detail
