### ISSUE TITLE
Super Mario 3D World + Bowser's Fury [v1.1.0]

### ISSUE THREAD

**Issue by Jueganator** [Fl4sh9174/Switch-Ultrawide-Mods#37]
Could you make a mod to disable dynamic resolution in both games?

**Comment by Fl4sh9174** [comment]
Theres already a mod in the folder that does disable dynamic resolution, but i named it 60fps handheld, i uploaded some new mods provided by another modder to leave the orignal resolution in handlheld mode, should have low end systems/switch.
