### ISSUE TITLE
Can you make one for DKC Tropical Freeze?

### ISSUE THREAD

**Issue by savdagod** [Fl4sh9174/Switch-Ultrawide-Mods#4]
Is it possible to make an UW mod for this game? thanks

**Comment by Fl4sh9174** [comment]
Sure, ill post it when i get home, i already made that mod, just forgot to upload it.

**Comment by savdagod** [comment]
Nice thanks, I can close this issue when you post it

**Comment by Fl4sh9174** [comment]
> Nice thanks, I can close this issue when you post it

Just added it, test and leave a feedback if you can.

**Comment by savdagod** [comment]
UW and 120fps works really well. I encountered a problem with the end of 3-K where the pendulum is supposed to fling you to the end. With 120fps enabled, you will not be launched therefore it's impossible to complete the level. Turning off the mod you get launched correctly. Not sure where else this happens but overall the mods work very well so thanks for posting them.

**Comment by Fl4sh9174** [comment]
> UW and 120fps works really well. I encountered a problem with the end of 3-K where the pendulum is supposed to fling you to the end. With 120fps enabled, you will not be launched therefore it's impossible to complete the level. Turning off the mod you get launched correctly. Not sure where else this happens but overall the mods work very well so thanks for posting them.

thank you for the feedback, can you send me the savefile so i can see if i fix it?
