### ISSUE TITLE
Need For Speed Hot Pursuit Remastered (Switch 21:9) on yuzu

### ISSUE THREAD

**Issue by ItzPritz** [Fl4sh9174/Switch-Ultrawide-Mods#40]
I've seen you made many widescreen patch and i really appreciate your work. Please make the 21:9 Widescreen Patch for Nfs HP remastered on switch (Yuzu). It's my favourite game but my eyes are hurting playing it at 16:9 ratio with black bars. (Don't add 60fps patch). I hope you see this🙏

**Comment by Fl4sh9174** [comment]
Done: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/Need%20For%20Speed%20Hot%20Pursuit%20Remastered%20%5B21.9%20Ultrawide%201.0.3%5D.zip

**Comment by ItzPritz** [comment]
> Done: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/Need%20For%20Speed%20Hot%20Pursuit%20Remastered%20%5B21.9%20Ultrawide%201.0.3%5D.zip

Omg, You don't know how happy I'm. Thank you so much..God bless you❤️
