### ISSUE TITLE
The Legend of Zelda: Echoes of Wisdom

### ISSUE THREAD

**Issue by SnowVXIII** [Fl4sh9174/Switch-Ultrawide-Mods#41]
The game has leaked today, can you please make 3440x1440 and 60 fps for this game? thank you for your eforts

**Comment by mauffix** [comment]
where please thank

**Comment by Fl4sh9174** [comment]
Done: https://ko-fi.com/Post/The-Legend-of-Zelda-Echoes-of-Wisdom-01008CF01BA-O5O713VNK1
