### ISSUE TITLE
Final Fantasy X/X-2 

### ISSUE THREAD

**Issue by SnowVXIII** [Fl4sh9174/Switch-Ultrawide-Mods#42]
Can you please make a ultra wide and 60 fps for those games? even the pc version doesn't suport that, thank you

**Comment by Fl4sh9174** [comment]
This game is very weird, i can make the ultrawide patch in cheat engine but can't make it work via pchtxt, if i find a way ill let you know.

60 FPS for this game looks pretty hard, all the physics in the game are tied to 30fps, unlocking the 60fps just speedup the game, and fixing everything gonna be hard.
