### ISSUE TITLE
The Legend of Zelda Echoes of Wisdom [v1.0.1]

### ISSUE THREAD

**Issue by Jueganator** [Fl4sh9174/Switch-Ultrawide-Mods#44]
Could you make a cheat to get 99 Monster Stones? I tried the Max Item cheat on GameBanana but it doesn't apply to Monster Stones.

**Comment by Fl4sh9174** [comment]
Im making mods to improve the game only, ask the guy who made the cheats on gamebanana page, maybe he can help you.
