### ISSUE TITLE
Burnout Paradise Remastered 

### ISSUE THREAD

**Issue by ItzPritz** [Fl4sh9174/Switch-Ultrawide-Mods#45]
I need 21:9 Widescreen patch for this game. It's running in 60 fps by default.

**Comment by Fl4sh9174** [comment]
Done, https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/Burnout%20Paradise%20Remastered%20%5B21.9%20Ultrawide%20v1.0.0%5D.zip

To stop preventing spamming of request, i will accept the KO-FI request only: https://Ko-fi.com/Fl4sh9174
