### ISSUE TITLE
Naruto x Boruto: Ultimate Ninja Storm Connections

### ISSUE THREAD

**Issue by Deka710** [Fl4sh9174/Switch-Ultrawide-Mods#46]
can you make ultrawide mod (20:9 if possible) for this game please? 1.50 latest patch update.

**Comment by Deka710** [comment]
> Done: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/NARUTO%20X%20BORUTO%20Ultimate%20Ninja%20STORM%20CONNECTIONS%20%5B21.9%20Ultrawide%20v1.5.0%5D.zip

thank you!!🤩

**Comment by Deka710** [comment]
> Done: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/NARUTO%20X%20BORUTO%20Ultimate%20Ninja%20STORM%20CONNECTIONS%20%5B21.9%20Ultrawide%20v1.5.0%5D.zip

wait this is work for any region? since mine is JP?

**Comment by Deka710** [comment]
![Screenshot_2024-10-07-02-09-19-733_org yuzu yuzu_emu](https://github.com/user-attachments/assets/6fc1b425-c070-4b64-b00a-e67c3331c373)
![Screenshot_2024-10-07-02-03-17-084_org yuzu yuzu_emu](https://github.com/user-attachments/assets/b4e2c2fa-9dcd-462e-aaf3-e40c365e14e6)
yeah it dont work, i tried it and its the same without the ultrawide mod.

**Comment by Fl4sh9174** [comment]
> > Done: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/NARUTO%20X%20BORUTO%20Ultimate%20Ninja%20STORM%20CONNECTIONS%20%5B21.9%20Ultrawide%20v1.5.0%5D.zip
> 
> wait this is work for any region? since mine is JP?, because i tried and it looks like dont work.

Since you didnt provide me the title ID, i used the version in the pchtxt, you can check the title ID version inside the pchtxt file.

**Comment by Deka710** [comment]
> > > Done: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/NARUTO%20X%20BORUTO%20Ultimate%20Ninja%20STORM%20CONNECTIONS%20%5B21.9%20Ultrawide%20v1.5.0%5D.zip
> > 
> > 
> > wait this is work for any region? since mine is JP?, because i tried and it looks like dont work.
> 
> Since you didnt provide me the title ID, i used the version in the pchtxt, you can check the title ID version inside the pchtxt file.

this is my Title ID
![Screenshot_2024-10-07-03-43-39-585_org yuzu yuzu_emu](https://github.com/user-attachments/assets/92d56dfa-b0dc-4d77-8865-9c1e7fc78f7e)

and this is inside the pchtxt
![Screenshot_2024-10-07-03-44-03-379_ru zdevs zarchiver](https://github.com/user-attachments/assets/edda4046-b769-4daa-b814-aabeab9cbb65)

**Comment by Deka710** [comment]
> > > > Done: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/NARUTO%20X%20BORUTO%20Ultimate%20Ninja%20STORM%20CONNECTIONS%20%5B21.9%20Ultrawide%20v1.5.0%5D.zip
> > > 
> > > 
> > > wait this is work for any region? since mine is JP?, because i tried and it looks like dont work.
> > 
> > 
> > Since you didnt provide me the title ID, i used the version in the pchtxt, you can check the title ID version inside the pchtxt file.
> 
> this is my Title ID ![Screenshot_2024-10-07-03-43-39-585_org yuzu yuzu_emu](https://private-user-images.githubusercontent.com/97207704/373978909-92d56dfa-b0dc-4d77-8865-9c1e7fc78f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNDgzNjYsIm5iZiI6MTcyODI0ODA2NiwicGF0aCI6Ii85NzIwNzcwNC8zNzM5Nzg5MDktOTJkNTZkZmEtYjBkYy00ZDc3LTg4NjUtOWMxZTdmYzc4ZjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDIwNTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZTY0MTYxMzM2NjE3Y2E4M2Y0OTY3ZGFmY2FhNWU3M2UzNjNkMmE2OTM0NmVkOTg5OTMxZTY1MjkwNGU0YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J0E41i7RRWZQSgypkkJtyfDBrgdy1SNpkZg1tpV5Has)
> 
> and this is inside the pchtxt ![Screenshot_2024-10-07-03-44-03-379_ru zdevs zarchiver](https://private-user-images.githubusercontent.com/97207704/373978949-edda4046-b769-4daa-b814-aabeab9cbb65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNDgzNjYsIm5iZiI6MTcyODI0ODA2NiwicGF0aCI6Ii85NzIwNzcwNC8zNzM5Nzg5NDktZWRkYTQwNDYtYjc2OS00ZGFhLWI4MTQtYWFiZWFiOWNiYjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDIwNTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMjMzMDFhNWEzNDRkNDJlNzFlZmI3NTY1ZjllZDg4YjUwNGZiNzlhMWU2ZjBkZDViYWQ0OTcwNGI5OTMyZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WlScx2qiEsEcvwo6T0a0qj95G_4NSGZb_DLYMiDVwPI)

wait i think i figured it out

**Comment by Deka710** [comment]
> > > > > Done: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/NARUTO%20X%20BORUTO%20Ultimate%20Ninja%20STORM%20CONNECTIONS%20%5B21.9%20Ultrawide%20v1.5.0%5D.zip
> > > > 
> > > > 
> > > > wait this is work for any region? since mine is JP?, because i tried and it looks like dont work.
> > > 
> > > 
> > > Since you didnt provide me the title ID, i used the version in the pchtxt, you can check the title ID version inside the pchtxt file.
> > 
> > 
> > this is my Title ID ![Screenshot_2024-10-07-03-43-39-585_org yuzu yuzu_emu](https://private-user-images.githubusercontent.com/97207704/373978909-92d56dfa-b0dc-4d77-8865-9c1e7fc78f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNDgzNjYsIm5iZiI6MTcyODI0ODA2NiwicGF0aCI6Ii85NzIwNzcwNC8zNzM5Nzg5MDktOTJkNTZkZmEtYjBkYy00ZDc3LTg4NjUtOWMxZTdmYzc4ZjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDIwNTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZTY0MTYxMzM2NjE3Y2E4M2Y0OTY3ZGFmY2FhNWU3M2UzNjNkMmE2OTM0NmVkOTg5OTMxZTY1MjkwNGU0YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J0E41i7RRWZQSgypkkJtyfDBrgdy1SNpkZg1tpV5Has)
> > and this is inside the pchtxt ![Screenshot_2024-10-07-03-44-03-379_ru zdevs zarchiver](https://private-user-images.githubusercontent.com/97207704/373978949-edda4046-b769-4daa-b814-aabeab9cbb65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNDgzNjYsIm5iZiI6MTcyODI0ODA2NiwicGF0aCI6Ii85NzIwNzcwNC8zNzM5Nzg5NDktZWRkYTQwNDYtYjc2OS00ZGFhLWI4MTQtYWFiZWFiOWNiYjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDIwNTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMjMzMDFhNWEzNDRkNDJlNzFlZmI3NTY1ZjllZDg4YjUwNGZiNzlhMWU2ZjBkZDViYWQ0OTcwNGI5OTMyZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WlScx2qiEsEcvwo6T0a0qj95G_4NSGZb_DLYMiDVwPI)
> 
> wait i think i figured it out

ok looks like changing Title ID also dont work maybe need different code, and im just gonna get that US version.
