### ISSUE TITLE
Crusin Blast

### ISSUE THREAD

**Issue by frixed** [Fl4sh9174/Switch-Ultrawide-Mods#47]
Can you make a 21:9 patch for Crusin Blast please

**Comment by Fl4sh9174** [comment]
Done: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/Cruis'n%20Blast%20%5B21.9%20Ultrawide%20v1.07%5D.zip

**Comment by frixed** [comment]
Thank you! :D
