### ISSUE TITLE
Naruto x Boruto: Ultimate Ninja Storm Connections patch issue

### ISSUE THREAD

**Issue by Deka710** [Fl4sh9174/Switch-Ultrawide-Mods#49]
![373973618-b4e2c2fa-9dcd-462e-aaf3-e40c365e14e6](https://github.com/user-attachments/assets/8660504d-a928-4e77-ab05-cf6f72bd63b0)
![373973608-6fc1b425-c070-4b64-b00a-e67c3331c373](https://github.com/user-attachments/assets/ddac340a-2cd1-4236-b6dc-afb0ce640505)
the ultrawide mod seems doesnt work, also can u include 720p Handheld because 1080 Docked too demanding😄.

**Comment by Fl4sh9174** [comment]
Use stretch to window option, you can change the values on the pchtxt to your needs, also dont use ultrawide mods with 1080P mod, it override eachother.

**Comment by Deka710** [comment]
> Use stretch to window option, you can change the values on the pchtxt to your needs, also dont use ultrawide mods with 1080P mod, it override eachother.

which tools to open pchtxt files?

**Comment by Deka710** [comment]
> Use stretch to window option, you can change the values on the pchtxt to your needs, also dont use ultrawide mods with 1080P mod, it override eachother.

any idea how to get the correct value? because i dont even know lol
