### ISSUE TITLE
Unicorn Overlord version

### ISSUE THREAD

**Issue by R0yl** [Fl4sh9174/Switch-Ultrawide-Mods#5]
hi, great work on the ultrawide patches!

For the Unicorn Overlord, my version is the asian one, with game id 010054B01AD92000. The mod is for 010069401ADB8000, and doesn't seem to work with mine version.

Would you check if it is possible  to make it work? thank you

**Comment by Fl4sh9174** [comment]
If you send me the main file i cant take a look if its possible to convert it.

**Comment by R0yl** [comment]
> If you send me the main file i cant take a look if its possible to convert it.

Good lord, appreciate your quick reply!
I uploaded the file, please find it here 
(https://drive.google.com/file/d/1y-WUvDwOvd5uVm6X9y3MwvC9Ehh4yNCd/view?usp=sharing)

**Comment by Fl4sh9174** [comment]
[Unicorn Overlod[21.9 Ultrawide v1.01].zip](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/files/14734754/Unicorn.Overlod.21.9.Ultrawide.v1.01.zip)
Test it and see if it works

**Comment by R0yl** [comment]
> [Unicorn Overlod[21.9 Ultrawide v1.01].zip](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/files/14734754/Unicorn.Overlod.21.9.Ultrawide.v1.01.zip) Test it and see if it works

Emmmm, i don't think it worked. When modded, felt quite strechy.
Did i missed thing, after for putting on "strech to window" then full screen yuzu?

**Comment by Fl4sh9174** [comment]
> > [Unicorn Overlod[21.9 Ultrawide v1.01].zip](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/files/14734754/Unicorn.Overlod.21.9.Ultrawide.v1.01.zip) Test it and see if it works
> 
> Emmmm, i don't think it worked. When modded, felt quite strechy. Did i missed thing, after for putting on "strech to window" then full screen yuzu?

You must extract this file in mods folder, using the update 1.0.1 with mod enabled, only that, if possible sent a screenshot showing you config.

**Comment by R0yl** [comment]
> > > [Unicorn Overlod[21.9 Ultrawide v1.01].zip](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/files/14734754/Unicorn.Overlod.21.9.Ultrawide.v1.01.zip) Test it and see if it works
> > 
> > 
> > Emmmm, i don't think it worked. When modded, felt quite strechy. Did i missed thing, after for putting on "strech to window" then full screen yuzu?
> 
> You must extract this file in mods folder, using the update 1.0.1 with mod enabled, only that, if possible sent a screenshot showing you config.

![20240325084554](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/20813918/3a8e5b67-0f37-473b-ad8e-c26c39d75650)
![20240325084549](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/20813918/e8924ba5-6a71-4a27-9384-193667e5a4b2)
![20240325084535](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/20813918/2ea0dff9-9735-4a55-a347-88b30af47ce0)

Thanks for your continued effort into this issue.

Config uploaded, almost all default. We have some time difference, so i tried the US version of the game, and modded with your patch of 010069401ADB8000. Didn't work. Then i tried your mod for "zelda tears of the kingdom", OMG it worked smoothly with 21:9. and proof was, when I used window mode (16:9 ), there would be two black bars on each side.

**Comment by Fl4sh9174** [comment]
![169 (1)](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/153722828/27713c05-25ec-4e0d-b636-d5340d24d472)
![219 (1)](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/153722828/843722bb-2be5-4b31-9947-9549eec4056c)
[[21.9 Ultrawide v1.01][Asia].zip](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/files/14738020/21.9.Ultrawide.v1.01.Asia.zip)
This version is working, the file you sent me was outdated, thats why it wasnt working, you must send the main file of the latest update you are using.

**Comment by R0yl** [comment]
> 16:9 ![169 (1)](https://private-user-images.githubusercontent.com/153722828/316368011-27713c05-25ec-4e0d-b636-d5340d24d472.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzg5MDUsIm5iZiI6MTcxMTMzODYwNSwicGF0aCI6Ii8xNTM3MjI4MjgvMzE2MzY4MDExLTI3NzEzYzA1LTI1ZWMtNGUwZC1iNjM2LWQ1MzQwZDI0ZDQ3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMzUwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzkzNjhhM2IxYWMxNWIxNjE0NDAwNzUxNTA4YTk5ZmM1MmQxNjVhYTZmYjE1MjZmZDAzMmIyNTRiODBkNmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PRp23t9x80p2h6WU9s4egD-kCLmKTpcF-eDg_kXagBs) 21:9 Ultrawide ![219 (1)](https://private-user-images.githubusercontent.com/153722828/316368017-843722bb-2be5-4b31-9947-9549eec4056c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzg5MDUsIm5iZiI6MTcxMTMzODYwNSwicGF0aCI6Ii8xNTM3MjI4MjgvMzE2MzY4MDE3LTg0MzcyMmJiLTJiZTUtNGIzMS05OTQ3LTk1NDllZWM0MDU2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwMzUwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzcyYzU3YzE1NmU0ODNiMDVlMjU4YzE1ODM4MzU3MmM1MjhmNDQ2YzRlMWRhZmI5OGU5YzAzOTU4N2U5MDQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UjJ8JT6GgO47tTOMeJT6ij0L2NEh3pbx0le6zNGdQfo) [[21.9 Ultrawide v1.01][Asia].zip](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/files/14738020/21.9.Ultrawide.v1.01.Asia.zip) This version is working, the file you sent me was outdated, thats why it wasnt working, you must send the main file of the latest update you are using.

It worked! I'm so happy!

Thank you very much, so kind and helping modder you are.

**Comment by TimMahood** [comment]
Does this work with Version 1.05 of the game? (or anyway I can get it to work..?

**Comment by switchhax9** [comment]
@Fl4sh9174 any chance you could make a 20:9 ultrawide mod for [USA v1.05](https://buffdrive.com/bxx) ([all files](https://romsim.com/unicorn-overlord-switch/))?

**Comment by kratores85** [comment]
@Fl4sh9174 USA v1.05 21:9 or even better 19.5:9 (common mobile phone aspect ratio) would be amazing! Thanks in advance! :)
