### ISSUE TITLE
Crash Bandicoot 4 + N. Sane Trilogy

### ISSUE THREAD

**Issue by John-Ivar** [Fl4sh9174/Switch-Ultrawide-Mods#50]
I'm completely blown away by your work and dedication to figuring out these patches, so before I ask for anything, I just have to say THANK YOU for all you've done so far. My biggest games on my wishlist for 21:9 aspect ratios are the two Crash games Crash 4 and Crash N Sane Trilogy. I've been playing Nitro Fueled with your patch and it looks and feels absolutely awesome.

**Comment by Fl4sh9174** [comment]
Glad to hear that, each game is different so it require some thinkering, but ill add games when i have free time to do it.

**Comment by John-Ivar** [comment]
Excellent. Thank you for the quick and positive response. Take whatever time you need and don't feel pressured. We are just happy someone is skilled and kind enough to go through this effort.
