### ISSUE TITLE
120 fps donkeykong tropical freeze issue

### ISSUE THREAD

**Issue by rakantoh** [Fl4sh9174/Switch-Ultrawide-Mods#52]
the mod no works properly, unlock all the fps, the game runs very fast and after the intro video the game freezes.

**Comment by Fl4sh9174** [comment]
Make sure you are on the correct update.

**Comment by rakantoh** [comment]
yes, im in the correct update, i have knowledge about mods and how to configure/install, inclusive by myself update the 21.9 mod for mario kart 8 to 3.0.3 (isn't diffcult, it was easy), but when enable 120fps mod, the game runs at maximal fps that my pc can, and since start the game (only video) runs very fast, the audio runs normally, and at the end of the video, the game freezes and the audio start to sound like an damaged cd.
Other issue is with ultrawide mod for crast team racing nitro fueled, broke some graphic elements like buttons guide on bottomright screen and the start screen shows weird, similar to isometric image.

**Comment by Fl4sh9174** [comment]
Just tested here and its working, dunno what you are doing wrong...

**Comment by rakantoh** [comment]
nothing, the mods is in the correct place, nothing moved/deleted, only 120fps mod enabled, game updated to 1.0.2, on ryujinx is the problem, in yuzu emus works, but in yuzu emus many fps mods runs maximum to 120hz, i have a unlock fps mod for ctrnf and in ryujinx the game runs fine with the mod at more than 120 (~150), in yuzu emus runs always at 120fps, so, i think that ryujinx is a better emu to test the mods, in any case, i appreciate to you effort to give us to players this mods, many thanks!

**Comment by Fl4sh9174** [comment]
On Ryujinx you can cap the FPS using rivaturner or the gpu driver, most of the mods were made with Yuzu in mind, but i always try to make it compatible in both, thanks for the feedback.
