### ISSUE TITLE
Pikmin 4 Ultrawide mod doesn't actually change the camera's aspect ratio

### ISSUE THREAD

**Issue by rehtlaw** [Fl4sh9174/Switch-Ultrawide-Mods#57]
The Ultrawide mod for Pikmin 4 only moves the HUD, but doesn't actually expand the viewport.

![0100b7c00933a000_2024-11-06_11-22-08-564](https://github.com/user-attachments/assets/b42eca31-eea1-4bae-be85-db24950d040a)

**Comment by Fl4sh9174** [comment]
The mod work as expected on v1.0.2 only.

**Comment by rehtlaw** [comment]
ah, for some reason my update got disabled. It does actually work as expected.

**Comment by Fl4sh9174** [comment]
Np, Enjoy!
