### ISSUE TITLE
Pikmin 4 Ultrawide mod crashes on Ryujinx

### ISSUE THREAD

**Issue by rehtlaw** [Fl4sh9174/Switch-Ultrawide-Mods#58]
Seems like that mod crashes during startup on Ryujinx, while Yuzu works fine.
This specific report is from a recent version of GreemDev's fork, but as far as I can tell this also happened on the last official version.

[Ryujinx_1.2.59+b19293ec9357edddb6ec474d92ea0f8a852f0760_2024-11-06_16-12-20.log](https://github.com/user-attachments/files/17649085/Ryujinx_1.2.59%2Bb19293ec9357edddb6ec474d92ea0f8a852f0760_2024-11-06_16-12-20.log)

**Comment by Fl4sh9174** [comment]
Download again, Ryujinx isn't allowing disabling dynamic resolution, i made a workaround to see if it fixes the issue.

**Comment by rehtlaw** [comment]
yup, that fixed it. Thanks!
