### ISSUE TITLE
Could you please make a FPS mod for Inazuma Eleven Victory Road Beta?

### ISSUE THREAD

**Issue by SuperTavor** [Fl4sh9174/Switch-Ultrawide-Mods#6]
Would be super nice!

**Comment by Fl4sh9174** [comment]
https://cdn.discordapp.com/attachments/1175410743093493851/1223104509971140609/image.png?ex=6618a3d7&is=66062ed7&hm=6a03be156f06dc9dffe5b9c927728d6d5e0e36a9a6eb6aaa6bc3392758c60060&

i already made it, will release it soon.

**Comment by Fl4sh9174** [comment]
Just uploaded it, reopen the issue if something isnt working.
