### ISSUE TITLE
Metroid Prime Remastered at 3840x1600

### ISSUE THREAD

**Issue by InterClaw** [Fl4sh9174/Switch-Ultrawide-Mods#61]
I'm using your 21:9 3440x1440 mod, but would like to run it at 3840x1600 for an even better experience on my screen.

By comparing the mod with your other 16:9 resolution mods for this game, I believe these are the values that need to be modified:

00001248 **00AE8152**
00001250 **00B48052**

For the first one I believe it should be this value instead for 3840:

00001248 **00E08152**

But what should I put on the second one to get 1600?

00001250 **00??????**

**Comment by Fl4sh9174** [comment]
00001250  00C88052
