### ISSUE TITLE
Super Smash Bros Ultimate 120 FPS Definitive Edition - Gives 240 FPS

### ISSUE THREAD

**Issue by useranon350** [Fl4sh9174/Switch-Ultrawide-Mods#65]
When using the 120 FPS Definitive Edition mod, I end up with a 240FPS cap. Usually my FPS hovers around 150. Is this intended behavior?

EDIT: Turns out I can do 240FPS in 1v1 battles despite only doing 150FPS in the menu. Unfortunately, that means the battles are at double speed.

**Comment by Fl4sh9174** [comment]
Dont change the emulation speed in Yuzu.

**Comment by useranon350** [comment]
I am using Ryujinx and I have not touched anything related to emulation speed. I have left VSync on.

**Comment by Fl4sh9174** [comment]
Read the mod instructions, in ryujinx you must cap the FPS using driver or Rivaturner.

**Comment by useranon350** [comment]
Thanks for the answer, I'll do that. I don't see anything about FPS caps in either the repo README.md or the FPS MOD INSTRUCTIONS.txt though, is there a third file with further instructions?

**Comment by Fl4sh9174** [comment]
https://gamebanana.com/mods/499758

**Comment by useranon350** [comment]
Thanks, I was able to get it working with an FPS limiter.
