### ISSUE TITLE
Could you please do Yo-kai Watch Jam: Yo-kai Academy Y – Waiwai Gakuen Seikatsu?

### ISSUE THREAD

**Issue by SuperTavor** [Fl4sh9174/Switch-Ultrawide-Mods#7]
It should be similar to YKW4 and Inazuma, and would be incredible if it's not too much trouble!

**Comment by Fl4sh9174** [comment]
Post the title of this game, the specific version you want.

**Comment by Fl4sh9174** [comment]
Just uploaded a version i have here, i hope this works for you.

**Comment by SuperTavor** [comment]
Tried it out on Yuzu, Version 4.0.0 and it didn't work

**Comment by SuperTavor** [comment]
Ok I tried the 120fps patch on Ryujinx and got 600FPS. Succuss I guess? 💀

**Comment by Fl4sh9174** [comment]
I tested on yuzu and its working fine, all versions, on ryujinx you can limit fps using rivaturner if you want to, or leave at high fps if dont bother you.

**Comment by SuperTavor** [comment]
Tysm!
