### ISSUE TITLE
Mario party superstar widescreen glitch

### ISSUE THREAD

**Issue by pantomm** [Fl4sh9174/Switch-Ultrawide-Mods#8]
It made this mini game unplayable
![Screenshot_2024-04-01-17-07-17-136_org yuzu yuzu_emu](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/50849304/b7673216-1092-413d-99cb-c078cf17594b)
![Screenshot_2024-04-01-17-04-15-732_org yuzu yuzu_emu](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/50849304/5a84c42a-b97c-46f7-ab0c-0746ed67bbbd)

**Comment by Fl4sh9174** [comment]
> It made this mini game unplayable ![Screenshot_2024-04-01-17-07-17-136_org yuzu yuzu_emu](https://private-user-images.githubusercontent.com/50849304/318409037-b7673216-1092-413d-99cb-c078cf17594b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjgxMDcsIm5iZiI6MTcxMTk2NzgwNywicGF0aCI6Ii81MDg0OTMwNC8zMTg0MDkwMzctYjc2NzMyMTYtMTA5Mi00MTNkLTk5Y2ItYzA3OGNmMTc1OTRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMzUzZjc1OTYxN2E4ZWE4Nzc0ZGYwM2RlMjEzMmVkYzE4MjQ0ODQ2OWJhYzA0M2E2ZjVjOGNlOTgwNTk4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ka8R9mZ49GN-ON20Svsrt685R-1DMOsG_3_UpEc0HZ0) ![Screenshot_2024-04-01-17-04-15-732_org yuzu yuzu_emu](https://private-user-images.githubusercontent.com/50849304/318409080-5a84c42a-b97c-46f7-ab0c-0746ed67bbbd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjgxMDcsIm5iZiI6MTcxMTk2NzgwNywicGF0aCI6Ii81MDg0OTMwNC8zMTg0MDkwODAtNWE4NGM0MmEtYjk3Yy00NmY3LWFiMGMtMDc0NmVkNjdiYmJkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNmNlZmFjYjliYzU1Y2Y4M2NjNGZlZmJkMzFjM2JiMGM1NmMyNTNiZDZkYzc0OWExNGQ3M2MxOGExZWZjZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-VySZNx6ycQjXYaqOPf8BVIKhUa-J-hBk-xZUaY3mV8)

Thanks for the feedback, can you test this one and see if this minigame is fixed?
[[21.9 Ultrawide v1.1.1]test.zip](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/files/14822606/21.9.Ultrawide.v1.1.1.test.zip)

**Comment by pantomm** [comment]
It fixed but stretched, at least it's playable. Thank you

**Comment by Fl4sh9174** [comment]
[[21.9 Ultrawide v1.1.1].zip](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/files/14822885/21.9.Ultrawide.v1.1.1.zip)
Test this one and see if fixes the ratio.

**Comment by pantomm** [comment]
Perfecto 
![Screenshot_2024-04-01-19-30-56-602_org yuzu yuzu_emu](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/50849304/933e0e19-14bd-4c86-af38-b51364da0c72)
Can you make other mini games not stretch too, here's example
![Screenshot_2024-04-01-19-33-00-928_org yuzu yuzu_emu](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/50849304/fe7f6ec1-d62f-4dff-915a-1ab23595318c)

**Comment by Fl4sh9174** [comment]
Sure, just leave the name of the minigame and ill take a look, tell me if you find any issue in others minigames too.

**Comment by pantomm** [comment]
It mostly the 2v2 and 4v4 mini games that got stretched

**Comment by Fl4sh9174** [comment]
> It mostly the 2v2 and 4 players split screen mini games that got stretched

![mpar (1)](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/153722828/c1af2c91-cd6d-4464-9ad0-f8851c1fef01)
I think i found the correct function that controls the ar of this game, ill check some other to see if its fixed, dunno the side effects though.

**Comment by Fl4sh9174** [comment]
I updated the aspect ratio mod and added one that remove DOF if you want to test, tried some minigames and they are working fine with this new version, if you encounter any issues, feel free to reopen the issue.
