### ISSUE TITLE
Totk 1.2.1

### ISSUE THREAD

**Issue by pavelbarabanov** [Fl4sh9174/Switch-Ultrawide-Mods#9]
In gameplay, the picture is stretched

**Comment by Fl4sh9174** [comment]
[https://imgsli.com/MjUzODM0](url)
Just checked and mod is working fine, make sure to install it in the correct folder:
C:\Users\Username\AppData\Roaming\yuzu\load\0100F2C0115B6000

**Comment by pavelbarabanov** [comment]
the problem is on android, the menu, map and backpack are displayed correctly, but the gameplay of the game itself is stretched

**Comment by pavelbarabanov** [comment]
https://ibb.co/YRYqb39
https://ibb.co/s1sxnWx
https://ibb.co/nLTQX0g
https://ibb.co/8cFZk61
https://ibb.co/KhqG7Z5
https://ibb.co/SvMdHJm

**Comment by pavelbarabanov** [comment]
the second and third screenshots

**Comment by pavelbarabanov** [comment]
https://imgsli.com/MjU0MDMy

**Comment by pavelbarabanov** [comment]
It's working https://drive.google.com/file/d/1e2UNo-wP-n9Lo5YUYAQyzxAWGaGviFKV/view?usp=sharing for all version totk
made of https://github.com/Fruithapje21/TOTK-Ultrawide/releases/tag/v3.3.1
